name: ekayana
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a08'
    - '#9ca274'
    - '#756f4f'
    - '#429790'
    - '#cdda94'
  brandStrength: 0.8125
  lightness: 0.8254635399207473
  saturation: 0.1560913878493011
  rhythmicContrast: 0.38833231711760163
purpose: []
