name: ekayana
favicon: null
layout_spectrum: 0.32037189044058323
typography_spectrum: 0.14363427832722664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7547331247478724
  lightness: 0.8254635399207473
  saturation: 0.1560913878493011
  rhythmicContrast: 0.38833231711760163
purpose: []
